[build]
  command = "npm run build"
  publish = "dist"
  functions = "netlify/functions"

[dev]
  command = "npm run dev"
  targetPort = 5173
  functionsPort = 8888

[functions]
  node_bundler = "esbuild"
  included_files = [".env"]

[build.environment]
  NODE_ENV = "development"

[[redirects]]
  from = "/api/registrations/*"
  to = "/.netlify/functions/delete-registration/:splat"
  status = 200
  force = true

[[redirects]]
  from = "/api/registrations"
  to = "/.netlify/functions/get-registrations"
  status = 200
  force = true
  methods = ["GET"]

[[redirects]]
  from = "/api/registrations/*"
  to = "/.netlify/functions/delete-registration/:splat"
  status = 200
  force = true
  methods = ["DELETE", "OPTIONS"]
